# Generated by Django 2.1.1 on 2018-12-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_registration',
            name='username',
        ),
        migrations.RemoveField(
            model_name='interviewer_registration',
            name='username',
        ),
        migrations.RemoveField(
            model_name='manager_registration',
            name='username',
        ),
    ]
